In [ ]:
%pip install transformers

In [ ]:
%pip install transformers datasets

In [1]:
from datasets import load_dataset
dataset = load_dataset("csv", data_files="IMDB Dataset.csv")
# dataset= load_dataset("IMDB Dataset.csv")

/home/harpreet/miniconda3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
split_dataset = dataset["train"].train_test_split(test_size=0.2, seed=42)

In [3]:
dataset

DatasetDict({
    train: Dataset({
        features: ['review', 'sentiment'],
        num_rows: 50000
    })
})

In [4]:
dataset["train"][0]

{'review': "One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.",
 'sentiment': 'positive'}

Pre process the data

In [6]:
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
)

model_name = "distilbert-base-uncased"
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
print(dataset.column_names)

{'train': ['review', 'sentiment']}

Tokenize dataset

In [8]:
# 3. Combined Preprocessing Function
def preprocess_function(examples):
    # Tokenize
    result = tokenizer(examples["review"], truncation=True)
    # Convert 'positive'/'negative' strings directly to integers 1 and 0
    result["labels"] = [
        1 if sentiment == "positive" else 0
        for sentiment in examples["sentiment"]
    ]
    return result

In [9]:

tokenized_dataset = split_dataset.map(
    preprocess_function, batched=True, remove_columns=["review", "sentiment"]
)

In [10]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 40000
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
})

In [ ]:
%pip install torch

In [11]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 1142.65it/s]
[transformers] DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.weight       | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [12]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 40000
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
})

In [ ]:
tokenized_dataset["train"][0]

In [14]:
print("Updated columns:", tokenized_dataset["train"].column_names)

Updated columns: ['input_ids', 'token_type_ids', 'attention_mask', 'labels']

In [ ]:
%pip install transformers[torch]

In [ ]:
%pip install -U accelerate

In [15]:
import accelerate
print(accelerate.__version__)

1.14.0

In [16]:
small_train = tokenized_dataset["train"].select(range(5))
small_test = tokenized_dataset["test"].select(range(2))

In [17]:
from transformers import (
    DataCollatorWithPadding,
)
# 5. Data Collator (Handles padding AND tensor conversion dynamically per batch)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [18]:
print("Column Names:", small_train.column_names)

# Inspect the very first row
sample = small_train[0]
print("Keys in row 0:", sample.keys())

if "labels" in sample:
    print("Label value:", sample["labels"], "| Type:", type(sample["labels"]))

Column Names: ['input_ids', 'token_type_ids', 'attention_mask', 'labels']
Keys in row 0: dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])
Label value: 0 | Type: <class 'int'>

In [19]:
from transformers import TrainingArguments

try:
    training_args = TrainingArguments(
        output_dir="./results",
        learning_rate=2e-5,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=8,
        num_train_epochs=1,
        weight_decay=0.01,
        eval_strategy="epoch",
        use_cpu=True,
    )
except TypeError:
    training_args = TrainingArguments(
        output_dir="./results",
        learning_rate=2e-5,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        num_train_epochs=1,
        weight_decay=0.01,
        evaluation_strategy="epoch",
        use_cpu=True,
    )

Step - Intialize the model

In [20]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train,
    eval_dataset=small_test,
    data_collator=data_collator,
)

In [21]:
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.12it/s]

TrainOutput(global_step=3, training_loss=0.7223296165466309, metrics={'train_runtime': 9.7998, 'train_samples_per_second': 0.51, 'train_steps_per_second': 0.306, 'total_flos': 215259522816.0, 'train_loss': 0.7223296165466309, 'epoch': 1.0})

In [22]:
resul= trainer.evaluate()

In [23]:
resul

{'eval_loss': 0.6885846257209778}

In [ ]:
save_directory = "./my_imdb_distilbert"

# Save the model weights and configuration
model.save_pretrained(save_directory)

# Save the tokenizer files (vocabulary, special tokens configs)
tokenizer.save_pretrained(save_directory)
print(f"Model and tokenizer successfully saved to {save_directory}!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.59it/s]

('./my_imdb_distilbert/tokenizer_config.json',
 './my_imdb_distilbert/tokenizer.json')

- Run Live Inference on Custom Text

In [24]:
import torch

# Prepare input
text = "This movie was absolutely incredible!"
inputs = tokenizer(text, return_tensors="pt")

- Predict

In [25]:

with torch.no_grad():
    logits = model(**inputs).logits
    probabilities = torch.softmax(logits, dim=-1)
    prediction = torch.argmax(probabilities, dim=-1).item()

print("Positive" if prediction == 1 else "Negative")

Positive

## Arxiv

In [ ]:
%pip install arxiv

In [24]:
import arxiv
import pandas as pd

In [25]:
#query to 
query="ai or artificial intelligence or machine learning"
search=arxiv.Search(query=query,max_results=10,sort_by=arxiv.SortCriterion.SubmittedDate)

In [26]:
client = arxiv.Client(
    page_size=5,
    delay_seconds=3
)

# search = arxiv.Search(
#     query="large language model",
#     max_results=3
# )
# Fetch results
# papers = []
papers = [
    {
        "title": "Test AI Paper",
        "abstract": "This is test abstract",
        "published": "2024"
    }
]

# for result in client.results(search):
#     papers.append({
#         "title": result.title,
#         # "Authors": ", ".join([author.name for author in result.authors]),
#         # "published": result.published,
#         # "abstract": result.summary,
#         # "categories": result.categories
#     })
df= pd.DataFrame(papers)

In [29]:
df = pd.DataFrame(papers)
abst= df['abstract'][0]
print(df['abstract'])

0    This is test abstract
Name: abstract, dtype: str

In [43]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# 1. Load tokenizer and model directly
model_name = "google/flan-t5-small"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

Loading weights: 100%|██████████| 190/190 [00:00<00:00, 2237.44it/s]
[transformers] The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

In [44]:
inputs = tokenizer(f"summarize: {abst}", return_tensors="pt", truncation=True, max_length=512)

In [45]:
# 3. Generate tokens
output_ids = model.generate(
    inputs["input_ids"],
    max_new_tokens=150,
    min_length=30,
    no_repeat_ngram_size=3
)

In [46]:
summary = tokenizer.decode(output_ids[0], skip_special_tokens=True)
print(summary)

summary: This is test abstract. This is a test abstract . .. a sample of the test abstract is ....