In [ ]:
%pip install transformers

In [ ]:
%pip install transformers datasets

In [60]:
from datasets import load_dataset
dataset = load_dataset("csv", data_files="IMDB Dataset.csv")
# dataset= load_dataset("IMDB Dataset.csv")

In [61]:
split_dataset = dataset["train"].train_test_split(test_size=0.2, seed=42)

In [62]:
dataset

DatasetDict({
    train: Dataset({
        features: ['review', 'sentiment'],
        num_rows: 50000
    })
})

In [63]:
dataset["train"][0]

{'review': "One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.",
 'sentiment': 'positive'}

In [64]:
print("hello")

hello

Pre process the data

In [108]:
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    Trainer,
    TrainingArguments,
)

model_name = "distilbert-base-uncased"
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)

In [66]:
print(dataset.column_names)

{'train': ['review', 'sentiment']}

Tokenize dataset

In [87]:
# 3. Combined Preprocessing Function
def preprocess_function(examples):
    # Tokenize
    result = tokenizer(examples["review"], truncation=True)
    # Convert 'positive'/'negative' strings directly to integers 1 and 0
    result["labels"] = [
        1 if sentiment == "positive" else 0
        for sentiment in examples["sentiment"]
    ]
    return result

In [93]:

tokenized_dataset = split_dataset.map(
    preprocess_function, batched=True, remove_columns=["review", "sentiment"]
)

In [94]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 40000
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
})

In [ ]:
%pip install torch

In [ ]:
# tokenized_dataset = tokenized_dataset.map(label_str_to_int, batched=True)

In [ ]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

In [96]:
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 40000
    })
    test: Dataset({
        features: ['input_ids', 'token_type_ids', 'attention_mask', 'labels'],
        num_rows: 10000
    })
})

In [75]:
# train_data = tokenized_dataset["train"]
# eval_data = tokenized_dataset["test"]

In [ ]:
tokenized_dataset["train"][0]

In [77]:
print("Updated columns:", tokenized_dataset["train"].column_names)

Updated columns: ['labels', 'input_ids', 'token_type_ids', 'attention_mask']

In [ ]:
%pip install transformers[torch]

In [ ]:
%pip install -U accelerate

In [98]:
import accelerate
print(accelerate.__version__)

1.14.0

In [99]:
small_train = tokenized_dataset["train"].select(range(5))
small_test = tokenized_dataset["test"].select(range(2))

In [110]:
from transformers import (
    DataCollatorWithPadding,
)
# 5. Data Collator (Handles padding AND tensor conversion dynamically per batch)
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [111]:
print("Column Names:", small_train.column_names)

# Inspect the very first row
sample = small_train[0]
print("Keys in row 0:", sample.keys())

if "labels" in sample:
    print("Label value:", sample["labels"], "| Type:", type(sample["labels"]))

Column Names: ['input_ids', 'token_type_ids', 'attention_mask', 'labels']
Keys in row 0: dict_keys(['input_ids', 'attention_mask', 'labels'])
Label value: tensor(0) | Type: <class 'torch.Tensor'>

In [114]:
from transformers import TrainingArguments

try:
    training_args = TrainingArguments(
        output_dir="./results",
        learning_rate=2e-5,
        per_device_train_batch_size=2,
        per_device_eval_batch_size=8,
        num_train_epochs=1,
        weight_decay=0.01,
        eval_strategy="epoch",
        use_cpu=True
    )
except TypeError:
  training_args = TrainingArguments(
      output_dir="./results",
      learning_rate=2e-5,
      per_device_train_batch_size=8,
      per_device_eval_batch_size=8,
      num_train_epochs=1,
      weight_decay=0.01,
      evaluation_strategy="epoch",
      use_cpu=True,
  )

Step - Intialize the model

In [115]:
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train,
    eval_dataset=small_test,
    data_collator=data_collator,
)

In [116]:
trainer.train()

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  4.15it/s]

TrainOutput(global_step=3, training_loss=0.7000912030537924, metrics={'train_runtime': 7.3872, 'train_samples_per_second': 0.677, 'train_steps_per_second': 0.406, 'total_flos': 215259522816.0, 'train_loss': 0.7000912030537924, 'epoch': 1.0})

In [119]:
resul= trainer.evaluate()

In [120]:
resul

{'eval_loss': 0.6780508756637573}

In [ ]:
save_directory = "./my_imdb_distilbert"

# Save the model weights and configuration
model.save_pretrained(save_directory)

# Save the tokenizer files (vocabulary, special tokens configs)
tokenizer.save_pretrained(save_directory)
print(f"Model and tokenizer successfully saved to {save_directory}!")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards: 100%|██████████| 1/1 [00:00<00:00,  2.59it/s]

('./my_imdb_distilbert/tokenizer_config.json',
 './my_imdb_distilbert/tokenizer.json')

## Arxiv

In [ ]:
%pip install arxiv

In [ ]:
import arxiv
import pandas as pd

In [ ]:
#query to 
query="ai or artificial intelligence or machine learning"
search=arxiv.Search(query=query,max_results=10,sort_by=arxiv.SortCriterion.SubmittedDate)

In [ ]:
client = arxiv.Client(
    page_size=5,
    delay_seconds=3
)

# search = arxiv.Search(
#     query="large language model",
#     max_results=3
# )
# Fetch results
# papers = []
papers = [
    {
        "title": "Test AI Paper",
        "abstract": "This is test abstract",
        "published": "2024"
    }
]

# for result in client.results(search):
#     papers.append({
#         "title": result.title,
#         # "Authors": ", ".join([author.name for author in result.authors]),
#         # "published": result.published,
#         # "abstract": result.summary,
#         # "categories": result.categories
#     })
df= pd.DataFrame(papers)

In [ ]:
df = pd.DataFrame(papers)
abst= df['abstract'][0]
print(df['abstract'])

0    This is test abstract
Name: abstract, dtype: str

In [ ]:
from transformers import pipeline

summarizer = pipeline(
    "text-generation",
    model="google/flan-t5-small"
)

Loading weights: 100%|██████████| 190/190 [00:00<00:00, 2767.77it/s]
The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.
The model 'T5ForConditionalGeneration' is not supported for text-generation. Supported models are ['PeftModelForCausalLM', 'AfmoeForCausalLM', 'ApertusForCausalLM', 'ArceeForCausalLM', 'AriaTextForCausalLM', 'BambaForCausalLM', 'BartForCausalLM', 'BertLMHeadModel', 'BertGenerationDecoder', 'BigBirdForCausalLM', 'BigBirdPegasusForCausalLM', 'BioGptForCausalLM', 'BitNetForCausalLM', 'BlenderbotForCausalLM', 'BlenderbotSmallForCausalLM', 'BloomForCausalLM', 'BltForCausalLM', 'CamembertForCausalLM', 'LlamaForCausalLM', 'CodeGenForCausalLM', 'CohereForCausalLM', 'Cohere2ForCausalLM', 'CpmAntForCausalLM', 'CTRLLMHeadModel', 'CwmForCausalLM', 'Data2VecTextForCausalLM', 'DbrxForCausalLM', 'DeepseekV2ForCausalLM', 'DeepseekV3ForCausalLM', 'DiffLlamaForCausalLM', 'DogeForCausalLM', 'Dots1ForCausalLM', 'ElectraForCausalLM', 'Emu3ForCausalLM', 'ErnieForCausalLM', 'Ernie4_5ForCausalLM', 'Ernie4_5_MoeForCausalLM', 'Exaone4ForCausalLM', 'ExaoneMoeForCausalLM', 'FalconForCausalLM', 'FalconH1ForCausalLM', 'FalconMambaForCausalLM', 'FlexOlmoForCausalLM', 'FuyuForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'Gemma3ForConditionalGeneration', 'Gemma3ForCausalLM', 'Gemma3nForConditionalGeneration', 'Gemma3nForCausalLM', 'GitForCausalLM', 'GlmForCausalLM', 'Glm4ForCausalLM', 'Glm4MoeForCausalLM', 'Glm4MoeLiteForCausalLM', 'GlmMoeDsaForCausalLM', 'GotOcr2ForConditionalGeneration', 'GPT2LMHeadModel', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GPTNeoForCausalLM', 'GPTNeoXForCausalLM', 'GPTNeoXJapaneseForCausalLM', 'GptOssForCausalLM', 'GPTJForCausalLM', 'GraniteForCausalLM', 'GraniteMoeForCausalLM', 'GraniteMoeHybridForCausalLM', 'GraniteMoeSharedForCausalLM', 'HeliumForCausalLM', 'HunYuanDenseV1ForCausalLM', 'HunYuanMoEV1ForCausalLM', 'Jais2ForCausalLM', 'JambaForCausalLM', 'JetMoeForCausalLM', 'Lfm2ForCausalLM', 'Lfm2MoeForCausalLM', 'LlamaForCausalLM', 'Llama4ForCausalLM', 'Llama4ForCausalLM', 'LongcatFlashForCausalLM', 'MambaForCausalLM', 'Mamba2ForCausalLM', 'MarianForCausalLM', 'MBartForCausalLM', 'MegatronBertForCausalLM', 'MiniMaxForCausalLM', 'MiniMaxM2ForCausalLM', 'MinistralForCausalLM', 'Ministral3ForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'MllamaForCausalLM', 'ModernBertDecoderForCausalLM', 'MoshiForCausalLM', 'MptForCausalLM', 'MusicgenForCausalLM', 'MusicgenMelodyForCausalLM', 'MvpForCausalLM', 'NanoChatForCausalLM', 'NemotronForCausalLM', 'NemotronHForCausalLM', 'OlmoForCausalLM', 'Olmo2ForCausalLM', 'Olmo3ForCausalLM', 'OlmoHybridForCausalLM', 'OlmoeForCausalLM', 'OpenAIGPTLMHeadModel', 'OPTForCausalLM', 'PegasusForCausalLM', 'PersimmonForCausalLM', 'PhiForCausalLM', 'Phi3ForCausalLM', 'Phi4MultimodalForCausalLM', 'PhimoeForCausalLM', 'PLBartForCausalLM', 'ProphetNetForCausalLM', 'Qwen2ForCausalLM', 'Qwen2MoeForCausalLM', 'Qwen3ForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5MoeForCausalLM', 'Qwen3_5ForCausalLM', 'Qwen3MoeForCausalLM', 'Qwen3NextForCausalLM', 'RecurrentGemmaForCausalLM', 'ReformerModelWithLMHead', 'RemBertForCausalLM', 'RobertaForCausalLM', 'RobertaPreLayerNormForCausalLM', 'RoCBertForCausalLM', 'RoFormerForCausalLM', 'RwkvForCausalLM', 'SeedOssForCausalLM', 'SmolLM3ForCausalLM', 'SolarOpenForCausalLM', 'StableLmForCausalLM', 'Starcoder2ForCausalLM', 'TrOCRForCausalLM', 'VaultGemmaForCausalLM', 'WhisperForCausalLM', 'XGLMForCausalLM', 'XLMWithLMHeadModel', 'XLMRobertaForCausalLM', 'XLMRobertaXLForCausalLM', 'XLNetLMHeadModel', 'xLSTMForCausalLM', 'XmodForCausalLM', 'YoutuForCausalLM', 'ZambaForCausalLM', 'Zamba2ForCausalLM'].

NameError: name 'text' is not defined

In [ ]:
summary = summarizer(
    "summarize: Artificial intelligence is transforming industries...",
    max_length=50
)
print(summary)

Passing `generation_config` together with generation-related arguments=({'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
Both `max_new_tokens` (=256) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[{'generated_text': 'summarize: Artificial intelligence is transforming industries...transforming the way they conduct, and the way they do what they do.'}]